FROM node:20

WORKDIR /usr/src/app

# Copy package.json and package-lock.json first to install dependencies
COPY package*.json ./

# Install app dependencies
RUN npm install

COPY . .


EXPOSE 3000

CMD ["node", "src/server.js"]
