version: '3.3'

services:
  webauthn-server:
    image: websignature-server:v91124
    build:
      context: .
      dockerfile: ../docker/Dockerfile.webauth
    env_file:
      - .env
    ports:
      - "3300:3000"
    environment:
      - PORT=3000
      - RP_ID=${RP_ID}                # Load RP_ID from .env
      - JWT_SECRET=${JWT_SECRET}      # Load JWT_SECRET from .env
    volumes:
      - .:/usr/src/app
    networks:
      - webauthn-net

networks:
  webauthn-net:
    driver: bridge
